import CreatePost from "@/components/CreatePost";
import { Container } from "@chakra-ui/react";
import Head from "next/head";

export default function PostsAdd() {
  return (
    <>
      <Head>
        <title>Posts | Add</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl" p={0}>
        <CreatePost />
      </Container>
    </>
  );
}
