import Head from "next/head";
import { Container } from "@chakra-ui/react";
import Posts from "../components/Posts";

export default function Home() {
  return (
    <>
      <Head>
        <title>Posts</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW="container.xl" p={0}>
        <Posts />
      </Container>
    </>
  );
}
